
version: "3.1"

services:
  database:
    build: 
       context: database
    image: ddev_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB: ddev
    ports:
      - "5432:5432" 
    networks:
      - back-tier

  api:
    build:
       context: api
       dockerfile: Dockerfile-dev
    image: ddev_api
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - front-tier
      - back-tier
    env_file:
      - env-dev.conf

  ui:
    build:
      context: ui
    image: ddev_ui
    ports:
      - "3000:3000"
    networks:
      - front-tier
    
networks:
  front-tier:
  back-tier:
